# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: $dockerhub_repo CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  dockerhub_id: benjaminfiche77
  dockerhub_repo: fast-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test python Code
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
          cd app/
          pytest

  build-push-container:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build -t $dockerhub_id/$dockerhub_repo:${GITHUB_SHA} .
          docker tag  $dockerhub_id/$dockerhub_repo:${GITHUB_SHA} $dockerhub_id/$dockerhub_repo:latest
          docker images
          docker run -d -p 80:80 --name fastapi $dockerhub_id/$dockerhub_repo:${GITHUB_SHA}
          sleep 10
          docker login -u ${{ secrets.REGISTRY_USER  }} -p ${{ secrets.REGISTRY_PASSWD  }}
          docker push $dockerhub_id/$dockerhub_repo:${GITHUB_SHA}
          docker push $dockerhub_id/$dockerhub_repo:latest

  deploy:
    needs: build-push-container
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        # uses: easingthemes/ssh-deploy@main
        # with:
        #   SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        #   REMOTE_HOST: ${{ secrets.HOSTNAME }}
        #   REMOTE_USER: ${{ secrets.USER_NAME }}
        #   SCRIPT_AFTER: |
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USER_NAME  }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          port: 22 
          script: |
            sudo docker rm -f fastapi 
            sudo docker rmi benjaminfiche77/fast-api:latest
            sleep 10 
            sudo docker run -d -p 9000:80 --name fastapi benjaminfiche77/fast-api:latest
            sudo docker ps 
            sleep 10 
            curl localhost:9000
            ls 
            sudo docker images
